services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    #volumes:
    #  - data/mongodb:/data/db
  mongo-explorer:
    container_name: mongo-explorer
    image: adicom/admin-mongo
    ports:
      - 8282:1234